services:
  snapotter:
    container_name: SnapOtter
    ports:
      - 1349:1349
    volumes:
      - ./data:/data
    image: snapotter/snapotter:latest
    networks:
      lan_net:
        ipv4_address: 10.17.15.2
    mem_limit: 6g
    memswap_limit: 6g
networks:
  lan_net:
    external: true
    name: lan_net
